version: '3.8'

services:
  backend:
    build:
      context: ./PlacementTracker_backend
    container_name: placement-backend
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/placementTracker
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
      JWT_SECRET: your-256-bit-secret-your-256-bit-secret
    networks:
      - app-network

  frontend:
    build:
      context: ./PlacementTracker_frontend
    container_name: placement-frontend
    ports:
      - "3000:80"
    depends_on:
      - backend
    environment:
      - REACT_APP_API_URL=http://backend:8080
    networks:
      - app-network

  db:
    image: postgres:15
    container_name: placement-db
    environment:
      POSTGRES_DB: placementTracker
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - app-network

volumes:
  postgres-data:

networks:
  app-network:
